import "~/styles/globals.css";

import { Montserrat } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";

const font = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Aulao - novas tecnologias",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`${font.className} min-h-screen overflow-x-hidden bg-gradient-to-br from-slate-950 to-cyan-900 text-slate-50 antialiased`}
      >
        <TRPCReactProvider>
          <h1>Layout da root</h1>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
